id = "clice"
name = "clice"
version = "0.1.0"
schema_version = 1
authors = ["clice-io"]
description = "C++ support"
repository = "https://github.com/clice-io/clice"

[language_servers.clice]
name = "clice"
language = "C++"
