name: format

on:
  workflow_call:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pixi
        with:
          environments: format

      - name: Run formatter
        run: pixi run format
        continue-on-error: true

      - name: Auto correct
        uses: huacnlee/autocorrect-action@v2
        with:
          args: --lint ./docs
        continue-on-error: true

      - name: Suggest changes
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-suggester@v1.24.0
        with:
          tool_name: "fmt"
          fail_level: any
          filter_mode: nofilter
