name: cmake

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            build_type: RelWithDebInfo
          - os: ubuntu-24.04
            build_type: Debug
          - os: macos-15
            build_type: Debug
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pixi
        with:
          environments: develop

      - name: Build
        run: pixi run ci-cmake-build ${{ matrix.build_type }}

      - name: Test
        run: pixi run ci-cmake-test
